"""
Public API of the ``shared`` module: paths, logging and database access.

This is the only entry point other modules may import from ``shared``. It owns
the project's directory layout so that no other module has to guess where the
source PDFs, the SQLite catalog, the generated images or the logs live.

The desktop build has no configuration system at all: every path is a module
constant derived from this file's location. The web deployment needs the data
directory to point at a mounted volume (``/data/az700`` in the container), so
three environment variables can override the defaults below. Nothing else in
the project reads the environment directly - this module is the single seam.

Example:
    >>> from api.modules.shared.api import get_logger, get_connection, IMAGES_DIR
    >>> log = get_logger(__name__)
    >>> log.info("images go to %s", IMAGES_DIR)
    >>> with get_connection() as conn:
    ...     conn.execute("SELECT 1").fetchone()[0]
    1
"""

from __future__ import annotations

import logging
import os
import sqlite3
from pathlib import Path

from api.modules.shared.internal import _db, _logging

#: Repository root, derived from this file's location (``<root>/api/modules/shared/api.py``).
PROJECT_ROOT: Path = Path(__file__).resolve().parents[3]

#: Input PDFs supplied by the user (read-only for this application). Only the
#: offline ``ingest`` build reads this; not overridable, since it never runs
#: in the deployed container.
SOURCE_DIR: Path = PROJECT_ROOT / "source"

#: Everything generated by the dataset build: the SQLite catalog and the
#: question/answer images. Excluded from version control. Overridable with
#: ``AZ700_DATA_DIR`` so the container can point it at a mounted volume.
DATA_DIR: Path = Path(os.environ.get("AZ700_DATA_DIR", str(PROJECT_ROOT / "data")))

#: One PNG per question region and one per answer region.
IMAGES_DIR: Path = DATA_DIR / "images"

#: HTML contact sheet used to verify the extraction by eye.
REPORT_DIR: Path = DATA_DIR / "report"

#: SQLite catalog: questions, exam sessions and statistics.
#: Overridable with ``AZ700_DB_PATH`` independently of ``AZ700_DATA_DIR``.
DB_PATH: Path = Path(os.environ.get("AZ700_DB_PATH", str(DATA_DIR / "az700.sqlite")))

#: Log directory and the rotating log file all runs append to.
#: Overridable with ``AZ700_LOGS_DIR`` (defaults under the data directory in
#: the container, so logs land on the same persistent volume).
LOGS_DIR: Path = Path(os.environ.get("AZ700_LOGS_DIR", str(PROJECT_ROOT / "logs")))
LOG_FILE: Path = LOGS_DIR / "az700.log"

# Re-exported so callers do not need to know about the internal helpers.
apply_migrations = _db.apply_migrations
get_run_id = _logging.get_run_id


def ensure_directories() -> None:
    """Create the generated-output directories if they do not exist yet."""
    for directory in (DATA_DIR, IMAGES_DIR, REPORT_DIR, LOGS_DIR):
        directory.mkdir(parents=True, exist_ok=True)


def get_logger(name: str, console_level: int = logging.INFO) -> logging.Logger:
    """
    Return a configured logger, setting up handlers on first use.

    Args:
        name: Logger name, normally the caller's ``__name__``.
        console_level: Console verbosity. Only honoured by the first call in the
            process, because handlers are installed exactly once.

    Returns:
        A logger writing to both the console and :data:`LOG_FILE`, with the run
        identifier stamped on every record.
    """
    _logging.configure_logging(LOG_FILE, console_level=console_level)
    return _logging.get_logger(name)


def get_connection(db_path: Path | None = None) -> sqlite3.Connection:
    """
    Open a connection to the project's SQLite database.

    Args:
        db_path: Database file to open. Defaults to :data:`DB_PATH`; tests pass a
            temporary path here.

    Returns:
        An open connection with foreign keys enforced and row access by name.
    """
    return _db.connect(db_path or DB_PATH)


# code-documentation-2026-09-05T18:24:39
